apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-alt
  namespace: monitoring
spec:
  serviceName: elasticsearch-alt
  replicas: 2  
  selector:
    matchLabels:
      app: elasticsearch-alt
  template:
    metadata:
      labels:
        app: elasticsearch-alt
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: "monitoring-alt"
        - name: discovery.seed_hosts
          value: "elasticsearch-alt-0.elasticsearch,elasticsearch-alt-1.elasticsearch"
        - name: cluster.initial_master_nodes
          value: "elasticsearch-alt-0,elasticsearch-alt-1"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"  # Augmentation de la mémoire Java
        resources:
          requests:
            memory: "2Gi"  # Augmentation des ressources
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
